service: spent-service-feed

frameworkVersion: '2'

plugins:
  # serverless reserve $ then use pseudo to interpolate # -> $
  - serverless-pseudo-parameters
  - serverless-plugin-typescript
  - serverless-offline
  - serverless-iam-roles-per-function

package:
  individually: true

custom: ${file(../../serverless.common.yml):custom}

provider:
  name: aws
  runtime: nodejs12.x
  memorySize: 256
  stage: ${opt:stage, 'dev'}
  region: ap-southeast-1
  tracing:
    apiGateway: true
    lambda: true
  environment:
    USERPOOL_ID: ${self:custom.userPoolId}
    ES_HOST: !ImportValue ${self:custom.spentApp}-ExtElasticsearchEndpoint
    ES_INDEX_RSS: rss-feed-2
  iamRoleStatements:
    - ${file(../../serverless.common.yml):lambdaPolicyXRay}

resources:
  # API Gateway Errors
  - ${file(resources/api-gateway-errors.yml)}
  # Cognito Identity Pool Policy
  - ${file(resources/cognito-policy.yml)}

  - Outputs:
      ApiGatewayRestApiId:
        Value:
          Ref: ApiGatewayRestApi
        Export:
          Name: ${self:custom.stage}-ExtApiGatewayRestApiId
      ApiGatewayRestApiRootResourceId:
        Value: !GetAtt ApiGatewayRestApi.RootResourceId
        Export:
          Name: ${self:custom.stage}-ExtApiGatewayRestApiRootResourceId

functions:
  hello:
    handler: src/handlers/hello.handler
    events:
      - http:
          method: GET
          path: feed/hello
          authorizer: ${self:custom.authorizer}
    iamRoleStatements:
      - Effect: Allow
        Action:
          - cognito-idp:*
        Resource:
          - ${self:custom.userPoolArn}
  feed:
    handler: src/handlers/feed.handler
    events:
      - http:
          method: GET
          path: /feed
          authorizer: ${self:custom.authorizer}
    iamRoleStatements:
      - Effect: Allow
        Action:
          - es:*
        Resource:
          - !ImportValue ${self:custom.spentApp}-ExtElasticsearchArn
          - !Join
            - ''
            - - !ImportValue ${self:custom.spentApp}-ExtElasticsearchArn
              - '/*'
