service: spent-service-user

frameworkVersion: '2'

plugins:
  # serverless reserve $ then use pseudo to interpolate # -> $
  - serverless-pseudo-parameters
  - serverless-plugin-typescript
  - serverless-offline
  - serverless-iam-roles-per-function
  # - serverless-dotenv-plugin
  - serverless-layers
  - serverless-deployment-bucket

package:
  individually: true

custom:
  stage: ${file(../../serverless.common.yml):custom.stage}
  spentApp: ${file(../../serverless.common.yml):custom.spentApp}
  spentAppMapping: ${file(../../serverless.common.yml):custom.spentAppMapping}
  userTable:
    name: ${file(../../serverless.common.yml):custom.dynamodb.userTable.name}
    arn: ${file(../../serverless.common.yml):custom.dynamodb.userTable.arn}

  serverless-layers:
    functions: # optional
      - get
      - list
    dependenciesPath: ./package.json

provider:
  name: aws
  runtime: nodejs12.x
  memorySize: 256
  stage: ${opt:stage, 'dev'}
  region: ap-southeast-1
  tracing:
    apiGateway: true
    lambda: true
  apiGateway:
    restApiId: !ImportValue ${self:custom.stage}-ExtApiGatewayRestApiId
    restApiRootResourceId: !ImportValue ${self:custom.stage}-ExtApiGatewayRestApiRootResourceId
  environment:
    USER_TABLE_NAME: ${self:custom.userTable.name}
  deploymentBucket:
    name: ${self:custom.spentApp}-service-user
    serverSideEncryption: AES256
  iamRoleStatements:
    - ${file(../../serverless.common.yml):lambdaPolicyXRay}
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
        - dynamodb:DescribeTable
      Resource: ${self:custom.userTable.arn}

functions:
  get:
    handler: src/handlers/get.handler
    events:
      - http:
          method: GET
          path: users/{id}
          authorizer: aws_iam
          request:
            parameters:
              paths:
                id: true

  list:
    handler: src/handlers/list.handler
    events:
      - http:
          method: GET
          path: users
          authorizer: aws_iam
