service: spent-service-user-api
# app and org for use with dashboard.serverless.com
# app: spent-resources
# org: thtiiz

frameworkVersion: '2'

plugins:
  - serverless-offline
  - serverless-pseudo-parameters
  - serverless-dotenv-plugin

package:
  individually: true
  exclude:
    - ./**
  include:
    - ./bin/**

provider:
  name: aws
  runtime: go1.x
  memorySize: 128
  stage: ${opt:stage, 'dev'}
  region: ap-southeast-1
  tracing:
    apiGateway: true
    lambda: true
  apiGateway:
    restApiId: !ImportValue ${self:custom.stage}-ExtApiGatewayRestApiId
    restApiRootResourceId: !ImportValue ${self:custom.stage}-ExtApiGatewayRestApiRootResourceId
  environment:
    TABLE_HISTORY: ${custom:dynamodb.tableHistory}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - 'dynamodb:Scan'
        - 'dynamodb:Query'
      Resource:
        - '*'

custom:
  stage: ${file(../../serverless.common.yml):custom.stage}
  spentApp: ${file(../../serverless.common.yml):custom.spentApp}
  spentAppMapping: ${file(../../serverless.common.yml):custom.spentAppMapping}

  dynamodb:
    tableHistory: ${env:TABLE_HISTORY}

functions:
  users:
    handler: bin/users
    events:
      - http:
          path: /users/{proxy+}
          method: ANY
