service: spent-service-google-trend

frameworkVersion: '2'

plugins:
  - serverless-pseudo-parameters
  - serverless-python-requirements
  - serverless-iam-roles-per-function
  - serverless-dotenv-plugin
  - serverless-offline

package:
  individually: true
  exclude:
    - node_modules/**

provider:
  name: aws
  runtime: python3.8
  memorySize: 256
  stage: ${opt:stage, 'dev'}
  versionFunctions: false
  region: ap-southeast-1
  tracing:
    apiGateway: true
    lambda: true
  environment:
    GOOGLE_ES_INDEX: ${self:custom.es.googleIndex}
    QUEUE_URL: !ImportValue ${self:custom.spentApp}-ExtCrawlerSQSUrl
  iamRoleStatements:
    - ${file(../../serverless.common.yml):lambdaPolicyXRay}
    - Effect: Allow
      Action: 'sqs:SendMessage'
      Resource: !ImportValue ${self:custom.spentApp}-ExtCrawlerSQSArn

custom:
  pythonRequirements:
    layer: true
    useStaticCache: true
    dockerizePip: non-linux

  crawConfig:
    timeout: 30
    rate: rate(1 hour)

  es:
    googleIndex: 'google-trends'

  stage: ${file(../../serverless.common.yml):custom.stage}
  spentApp: ${file(../../serverless.common.yml):custom.spentApp}
  spentAppMapping: ${file(../../serverless.common.yml):custom.spentAppMapping}

functions:
  googleCrawler:
    handler: handler.run
    layers:
      - { Ref: PythonRequirementsLambdaLayer }
    events:
      - schedule:
          rate: ${self:custom.crawConfig.rate}
          enabled: true
